# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: Check build for the library

on:
  pull_request:
  push:

jobs:
  build-check:
    runs-on: ubuntu-latest
    concurrency:
      group: build-check-${{ github.ref }}
      cancel-in-progress: true
    env:
      GRPC_VERSION: "1.69.0"
    steps:
    - uses: actions/checkout@v4
      with:
        path: astarte-device-sdk-cpp
    - name: Install gRPC dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential autoconf libtool pkg-config
    - name: Check out the gRPC repo
      run: git clone --recurse-submodules -b v${{ env.GRPC_VERSION }} --depth 1 --shallow-submodules https://github.com/grpc/grpc
    - name: Set MY_INSTALL_DIR variable
      run: |
        MY_INSTALL_DIR=$PWD/grpc-install
        echo "MY_INSTALL_DIR=$MY_INSTALL_DIR" >> $GITHUB_ENV
        mkdir -p $MY_INSTALL_DIR
        echo "$MY_INSTALL_DIR" >> "$GITHUB_PATH"
    - name: Restore cached gRPC build directory
      id: cache-grpc-cpp-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          ./grpc/cmake
          ./grpc-install
        key: grpc-cpp-v${{ env.GRPC_VERSION }}
    - name: Compile from source gRPC
      if: steps.cache-grpc-cpp-restore.outputs.cache-hit != 'true'
      run: |
        mkdir ./grpc/cmake/build
        pushd ./grpc/cmake/build
        cmake -DgRPC_INSTALL=ON \
              -DgRPC_BUILD_TESTS=OFF \
              -DCMAKE_CXX_STANDARD=17 \
              -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
              ../..
        make -j $(nproc)
        make install
        popd
    - name: Cache the gRPC build directory
      if: steps.cache-grpc-cpp-restore.outputs.cache-hit != 'true'
      id: cache-grpc-cpp-save
      uses: actions/cache/save@v4
      with:
        path: |
          ./grpc/cmake
          ./grpc-install
        key: ${{ steps.cache-grpc-cpp-restore.outputs.cache-primary-key }}
    - name: Build library for C++ 20
      working-directory: ./astarte-device-sdk-cpp
      run: |
        mkdir ./samples/build
        cd ./samples/build
        cmake -DUSE_SYSTEM_GRPC=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON ..
        make
    - name: Build library for C++ 17
      working-directory: ./astarte-device-sdk-cpp
      run: |
        rm -r ./samples/build
        mkdir ./samples/build
        cd ./samples/build
        cmake -DUSE_SYSTEM_GRPC=ON -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON ..
        make
