# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: Documentation generation

on:
  pull_request:
    paths:
    - 'README.md'
    - 'doc/**'
    - 'include/**'
    - '.github/workflows/doc.yml'

env:
  DOXYGEN_VERSION: 1.13.2

jobs:
  api-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    concurrency:
      group: api-docs-${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: astarte-device-sdk-cpp
    - name: Install doxygen
      shell: bash
      run: |
        wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
        tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH
    - name: Build API docs for C++ 20
      working-directory: astarte-device-sdk-cpp/doc
      run: |
        export DOXYGEN_ASTARTE_DEVICE_SDK_VERSION="0.5.0"
        export DOXYGEN_OUT="./_build"
        export DOXYGEN_ASTARTE_DEVICE_SDK_BASE="$PWD/.."
        export DOXYGEN_ASTARTE_DEVICE_SDK_MACROS="__cplusplus=202002L"
        doxygen astarte-device-sdk.doxyfile.in
    - name: Upload API HTML documentation for C++ 20
      uses: actions/upload-artifact@v4
      with:
        name: docs_html_cpp_20
        path: astarte-device-sdk-cpp/doc/_build/html
    - name: Build API docs for C++ 17
      working-directory: astarte-device-sdk-cpp/doc
      run: |
        rm -r ./_build
        export DOXYGEN_ASTARTE_DEVICE_SDK_VERSION="0.5.0"
        export DOXYGEN_OUT="./_build"
        export DOXYGEN_ASTARTE_DEVICE_SDK_BASE="$PWD/.."
        export DOXYGEN_ASTARTE_DEVICE_SDK_MACROS="__cplusplus=201703L"
        doxygen astarte-device-sdk.doxyfile.in
    - name: Upload API HTML documentation for C++ 17
      uses: actions/upload-artifact@v4
      with:
        name: docs_html_cpp_17
        path: astarte-device-sdk-cpp/doc/_build/html
