# (C) Copyright 2025, SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: Run the unit tests

on:
  pull_request:
  push:
defaults:
  run:
    shell: bash
env:
  GRPC_VERSION: "1.69.0"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: unit-tests-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
        with:
          path: astarte-device-sdk-cpp
      - name: Setup gRPC build cache
        id: cache-grpc-cpp
        uses: actions/cache@v4
        with:
          path: |
            ./grpc
            ./grpc-install
          # Cache the hash of the build script for the CMAKE flags
          key: grpc-cpp-v${{ env.GRPC_VERSION }}-${{ hashFiles('astarte-device-sdk-cpp/.github/scripts/build-grpc.sh') }}
      - name: Setup gRPC for build
        run: |
          ./astarte-device-sdk-cpp/.github/scripts/setup-grpc.sh "$GRPC_VERSION"
      - name: Compile gRPC from source
        run: |
          ./astarte-device-sdk-cpp/.github/scripts/build-grpc.sh
      - name: Build the unit tests (C++ 20)
        working-directory: ./astarte-device-sdk-cpp/unit
        run: |
          cmake -DASTARTE_USE_SYSTEM_GRPC=ON -DASTARTE_ENABLE_FORMAT=ON -DASTARTE_PUBLIC_PROTO_DEP=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_CXX_STANDARD_REQUIRED=ON -S . -B build
          cmake --build build
      - name: Run the unit tests
        working-directory: ./astarte-device-sdk-cpp/unit/build
        run: ctest || ./unit_test
      - name: Build the unit tests (C++ 17)
        working-directory: ./astarte-device-sdk-cpp/unit
        run: |
          rm -r ./build
          cmake -DASTARTE_USE_SYSTEM_GRPC=ON -DASTARTE_ENABLE_FORMAT=ON -DASTARTE_PUBLIC_PROTO_DEP=ON -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_STANDARD_REQUIRED=ON -S . -B build
          cmake --build build
      - name: Run the unit tests
        working-directory: ./astarte-device-sdk-cpp/unit/build
        run: ctest || ./unit_test
